### ISSUE TITLE
Checkbox to disable abilities costs

### ISSUE THREAD

**Issue by Arcahub** [Jad31/pokemon-card-maker#4]
It would be nice to have a checkbox to disable abilities costs since for me I don't find a relevant way to use them

**Comment by Jad31** [comment]
Could you please clarify whether your suggestion pertains to the costs associated with abilities or the damage they inflict? If you're focusing on the latter, I can modify the form to include an option for adding either an 'Ability' (which does not cause damage) or an 'Attack' (which does). This enhancement will provide users with the flexibility to choose having either one or two Abilities/Attacks, or even none, according to their preferences.
